import os
from dataclasses import dataclass
from typing import Dict, Optional

import numpy as np


@dataclass
class Employee:
    name: str
    embeddings: np.ndarray      # shape: (N, 128), N = number of enrolled images
    profile_image: Optional[str]  # absolute path to profile.jpg, or None


class FaceDatabase:
    """
    Loads and stores face embeddings for all enrolled employees.

    Expected on-disk layout:
        employees_dir/
            alice/
                img1.jpg
                img2.jpg
                embeddings.npy   ← generated by enroll.py
                profile.jpg      ← optional, shown in dashboard
            bob/
                ...
    """

    def __init__(self, employees_dir: str) -> None:
        self.employees_dir = employees_dir
        self.employees: Dict[str, Employee] = {}
        self._load()

    # ------------------------------------------------------------------
    # Public interface
    # ------------------------------------------------------------------

    def is_empty(self) -> bool:
        return len(self.employees) == 0

    def reload(self) -> None:
        """Re-scan the employees directory (e.g. after new enrollment)."""
        self.employees.clear()
        self._load()

    # ------------------------------------------------------------------
    # Internal loading
    # ------------------------------------------------------------------

    def _load(self) -> None:
        if not os.path.isdir(self.employees_dir):
            print(f"[face_db] ⚠ Employees directory not found: {self.employees_dir}")
            print("[face_db]   Create it and run enroll.py to register employees.")
            return

        loaded = 0
        for entry in sorted(os.listdir(self.employees_dir)):
            employee_dir = os.path.join(self.employees_dir, entry)
            if not os.path.isdir(employee_dir):
                continue

            emb_path = os.path.join(employee_dir, "embeddings.npy")
            if not os.path.exists(emb_path):
                print(f"[face_db] ⚠ {entry}: no embeddings.npy — run enroll.py first")
                continue

            try:
                embeddings = np.load(emb_path)
            except Exception as e:
                print(f"[face_db] ✗ Failed to load embeddings for {entry}: {e}")
                continue

            if embeddings.ndim != 2 or embeddings.shape[1] != 128:
                print(f"[face_db] ✗ {entry}: unexpected embedding shape {embeddings.shape}, skipping")
                continue

            profile_image = self._find_profile(employee_dir)

            self.employees[entry] = Employee(
                name=entry,
                embeddings=embeddings,
                profile_image=profile_image,
            )
            print(f"[face_db] ✓ {entry}: {len(embeddings)} embedding(s)"
                  + (f", profile: {os.path.basename(profile_image)}" if profile_image else ""))
            loaded += 1

        if loaded == 0 and os.path.isdir(self.employees_dir):
            print("[face_db] ⚠ No employees loaded. Run enroll.py to register employees.")

    @staticmethod
    def _find_profile(employee_dir: str) -> Optional[str]:
        for fname in ("profile.jpg", "profile.jpeg", "profile.png"):
            path = os.path.join(employee_dir, fname)
            if os.path.exists(path):
                return path
        return None
