import os
import cv2
import hashlib
import json
from pathlib import Path
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
from torchvision import transforms
import torchvision.models as models
from PIL import Image
import onnxruntime as ort

# ==========================================
# LOCAL MODEL PATHS (bundled at build time)
# ==========================================
MODELS_DIR = Path(__file__).parent / "models"
RECOG_LOCAL = MODELS_DIR / "pytorch_model.bin"
YOLO_LOCAL = MODELS_DIR / "yolov8s-face-lindevs.onnx"

# HuggingFace fallback (only used if local models are missing). 
# The regenerate-face-embedding.ts should run to clean up any legacy embeddings generated by different models if the local model isnt used 
HF_REPO_ID = os.getenv("HF_REPO_ID", "biometric-ai-lab/Face_Recognition")
HF_RECOG_FILENAME = "pytorch_model.bin"
HF_YOLO_FILENAME = "yolov8s-face-lindevs.onnx"

# Model version tracking — write a manifest when models are first loaded so we can
# detect stale caches and re-download only when the repo checkpoint actually changes.
VERSION_MANIFEST = MODELS_DIR / ".manifest.json"


def _compute_file_hash(path: Path) -> str:
    """SHA-256 hex digest of a file, used to detect model changes."""
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(8192), b""):
            h.update(chunk)
    return h.hexdigest()


def _ensure_models_downloaded() -> tuple[Path, Path]:
    """
    Return (recognition_model_path, yolo_detector_path).
    Uses local files if they exist; otherwise downloads from HF as a one-time fallback.
    """
    if RECOG_LOCAL.exists() and YOLO_LOCAL.exists():
        return RECOG_LOCAL, YOLO_LOCAL

    MODELS_DIR.mkdir(parents=True, exist_ok=True)

    try:
        from huggingface_hub import hf_hub_download

        recog_path = Path(
            hf_hub_download(
                repo_id=HF_REPO_ID,
                filename=HF_RECOG_FILENAME,
                cache_dir=str(MODELS_DIR.parent / ".hf_cache"),
            )
        )
        yolo_path = Path(
            hf_hub_download(
                repo_id=HF_REPO_ID,
                filename=HF_YOLO_FILENAME,
                cache_dir=str(MODELS_DIR.parent / ".hf_cache"),
            )
        )
        # Copy into the bundled models directory so Docker layers can cache them.
        import shutil

        shutil.copy2(recog_path, RECOG_LOCAL)
        shutil.copy2(yolo_path, YOLO_LOCAL)

        # Write version manifest for future change detection.
        manifest = {
            "hf_repo": HF_REPO_ID,
            "files": {
                HF_RECOG_FILENAME: _compute_file_hash(RECOG_LOCAL),
                HF_YOLO_FILENAME: _compute_file_hash(YOLO_LOCAL),
            },
        }
        VERSION_MANIFEST.write_text(json.dumps(manifest))
        print(f"✅ Downloaded models from {HF_REPO_ID} to local cache.")
        return RECOG_LOCAL, YOLO_LOCAL

    except Exception as exc:
        raise RuntimeError(
            f"❌ Failed to load or download models. Local files missing and HF download failed.\nError: {exc}"
        ) from exc


# ==========================================
# 1. MODEL ARCHITECTURE (Giống hệt code bạn)
# ==========================================
class FaceRecognitionModel(nn.Module):
    def __init__(self):
        super(FaceRecognitionModel, self).__init__()
        # Khởi tạo backbone, để weights=None vì ta sẽ load weight train của bạn
        self.backbone = models.wide_resnet101_2(weights=None)
        self.backbone.fc = nn.Identity()
        self.embed = nn.Sequential(
            nn.Linear(2048, 512),
            nn.BatchNorm1d(512),
            nn.ReLU(inplace=True),
        )

    def forward(self, img):
        features = self.backbone(img)
        embedding = self.embed(features)
        return F.normalize(embedding, p=2, dim=1)


# ==========================================
# 2. YOLO DETECTOR (Logic chuẩn của bạn)
# ==========================================
class YOLOFaceDetector:
    def __init__(self, model_path, conf_threshold=0.5):
        self.session = ort.InferenceSession(model_path, providers=['CUDAExecutionProvider', 'CPUExecutionProvider'])
        self.input_name = self.session.get_inputs()[0].name
        self.output_names = [output.name for output in self.session.get_outputs()]
        self.conf_threshold = conf_threshold
        self.input_size = 640

    def detect_extract_face(self, image_pil, expand_ratio=0.0):
        """
        Input: PIL Image
        Output: PIL Image (Cropped Face)
        """
        # Convert PIL -> OpenCV (BGR) để giống logic cũ
        image_np = np.array(image_pil)
        image_bgr = cv2.cvtColor(image_np, cv2.COLOR_RGB2BGR)
        img_height, img_width = image_bgr.shape[:2]

        # Preprocess (Resize -> RGB -> Norm -> Transpose)
        img_resized = cv2.resize(image_bgr, (self.input_size, self.input_size))
        # Lưu ý: YOLO training thường dùng RGB
        img_rgb = cv2.cvtColor(img_resized, cv2.COLOR_BGR2RGB)
        img_normalized = img_rgb.astype(np.float32) / 255.0
        img_transposed = np.transpose(img_normalized, (2, 0, 1))
        img_batch = np.expand_dims(img_transposed, axis=0)

        # Inference
        outputs = self.session.run(self.output_names, {self.input_name: img_batch})
        predictions = outputs[0]

        if len(predictions.shape) == 3:
            predictions = predictions[0].T

        best_face = None
        max_area = 0

        # Post-process
        for pred in predictions:
            conf = pred[4]
            if conf > self.conf_threshold:
                x_center, y_center, w, h = pred[:4]

                # Scale về ảnh gốc
                x_center = x_center * img_width / self.input_size
                y_center = y_center * img_height / self.input_size
                w = w * img_width / self.input_size
                h = h * img_height / self.input_size

                x1 = int(x_center - w / 2)
                y1 = int(y_center - h / 2)
                x2 = int(x_center + w / 2)
                y2 = int(y_center + h / 2)

                x1 = max(0, x1)
                y1 = max(0, y1)
                x2 = min(img_width, x2)
                y2 = min(img_height, y2)

                area = (x2 - x1) * (y2 - y1)

                # Lấy mặt to nhất
                if area > max_area:
                    max_area = area
                    best_face = (x1, y1, x2, y2)

        # Crop ảnh
        if best_face:
            x1, y1, x2, y2 = best_face

            # Xử lý expand_ratio (nếu có dùng)
            if expand_ratio != 0:
                w_box = x2 - x1
                h_box = y2 - y1
                pad = int(expand_ratio * max(w_box, h_box))
                x1 = max(0, x1 - pad)
                y1 = max(0, y1 - pad)
                x2 = min(img_width, x2 + pad)
                y2 = min(img_height, y2 + pad)

            # Crop từ ảnh gốc PIL (để giữ chất lượng tốt nhất)
            return image_pil.crop((x1, y1, x2, y2))

        print("⚠️ Warning: No face detected.")
        return None


# ==========================================
# 3. FACE ANALYSIS WRAPPER
# ==========================================
class FaceAnalysis:
    def __init__(self, device=None):
        self.device = device if device else ('cuda' if torch.cuda.is_available() else 'cpu')
        print(f"🚀 Initializing Face Analysis on {self.device}...")

        # 1. Resolve model paths (local first, HF fallback)
        recog_path, yolo_path = _ensure_models_downloaded()

        # 2. Init YOLO
        self.yolo = YOLOFaceDetector(str(yolo_path), conf_threshold=0.5)

        # 3. Init Recognition
        self.model = FaceRecognitionModel().to(self.device)

        # Load weights an toàn
        checkpoint = torch.load(recog_path, map_location=self.device)
        if isinstance(checkpoint, dict):
            if 'model' in checkpoint:
                state_dict = checkpoint['model']
            elif 'model_state_dict' in checkpoint:
                state_dict = checkpoint['model_state_dict']
            elif 'state_dict' in checkpoint:
                state_dict = checkpoint['state_dict']
            else:
                # Fallback nếu file dict là state_dict trực tiếp
                state_dict = checkpoint
        else:
            state_dict = checkpoint

        self.model.load_state_dict(state_dict)

        self.model.eval()

        # 4. Transform (Giống hệt inference_transform của bạn)
        self.transform = transforms.Compose([
            transforms.Resize((224, 224)),
            transforms.ToTensor(),
            transforms.Normalize(
                mean=[0.485, 0.456, 0.406],
                std=[0.229, 0.224, 0.225],
            ),
        ])
        print("✅ System Ready!")

    def process_image(self, image_source, expand_ratio=0.0):
        # Load ảnh
        if isinstance(image_source, str):
            if not os.path.exists(image_source):
                raise FileNotFoundError(f"Image not found: {image_source}")
            img_pil = Image.open(image_source).convert('RGB')
        elif isinstance(image_source, Image.Image):
            img_pil = image_source.convert('RGB')
        elif isinstance(image_source, np.ndarray):
            img_pil = Image.fromarray(cv2.cvtColor(image_source, cv2.COLOR_BGR2RGB))
        else:
            raise ValueError("Input must be filepath, PIL Image, or Numpy Array")

        # 1. YOLO Detect & Crop
        face_crop = self.yolo.detect_extract_face(img_pil, expand_ratio=expand_ratio)
        if face_crop is None:
            raise RuntimeError("No face detected. Please retake photo.")

        # 2. Transform & Embedding
        img_tensor = self.transform(face_crop).unsqueeze(0).to(self.device)

        with torch.no_grad():
            embedding = self.model(img_tensor)

        return embedding

    def compare(self, img1, img2, threshold=0.45, expand_ratio=0.01):
        """
        So sánh 2 ảnh.
        expand_ratio=0.01 giống code demo của bạn.
        """
        emb1 = self.process_image(img1, expand_ratio)
        emb2 = self.process_image(img2, expand_ratio)

        # Cosine Similarity
        similarity = F.cosine_similarity(emb1, emb2).item()
        is_same = similarity > threshold

        return similarity, is_same