-- Previous version database schema
-- Place the v1 database schema or relevant table definitions here.
-- This is reference material for understanding the data model and migration paths.
-- Do not use this file for migrations — use Prisma for all schema changes.

-- Example:
-- CREATE TABLE users (
--   id          INT PRIMARY KEY AUTO_INCREMENT,
--   email       VARCHAR(255) NOT NULL UNIQUE,
--   created_at  DATETIME NOT NULL DEFAULT NOW()
-- );
